/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ehg3jSSsQvNW6bvQabRQLY
// Component: e8sLLHz2kmWN

import * as React from "react";
import { DefaultHomepageProps } from "./PlasmicHomepage"; // plasmic-import: e8sLLHz2kmWN/render

import { ClientHomepage } from "../../../app/page-client"; // plasmic-import: e8sLLHz2kmWN/rscClient

const $$ = {};

import {
  executeServerQuery,
  mkPlasmicUndefinedServerProxy,
  ServerQuery,
  makeQueryCacheKey
} from "@plasmicapp/react-web/lib/data-sources";

export async function executeServerQueries($ctx: any) {
  const serverQueries: Record<
    string,
    ServerQuery<(typeof $$)[keyof typeof $$]>
  > = {};

  const queryVarToKey: Record<string, string> = {};
  const $queries: Record<string, any> = {};

  for (const key of Object.keys(serverQueries)) {
    const sq = serverQueries[key];
    const params = sq.execParams();
    const cacheKey = makeQueryCacheKey(sq.id, params);
    queryVarToKey[key] = cacheKey;
    $queries[cacheKey] = mkPlasmicUndefinedServerProxy();
  }

  do {
    await Promise.all(
      Object.keys(serverQueries).map(async key => {
        const cacheKey = queryVarToKey[key];
        $queries[cacheKey] = (
          await executeServerQuery(serverQueries[key])
        ).data;
        if (!$queries[cacheKey]?.isUndefinedServerProxy) {
          delete serverQueries[key];
        }
      })
    );
  } while (
    Object.values($queries).some(value => value?.isUndefinedServerProxy)
  );

  return $queries;
}

function mkPathFromRouteAndParams(
  route: string,
  params: Record<string, string | string[] | undefined>
) {
  if (!params) {
    return route;
  }
  let path = route;
  for (const [key, value] of Object.entries(params)) {
    if (typeof value === "string") {
      path = path.replace(`[${key}]`, value);
    } else if (Array.isArray(value)) {
      if (path.includes(`[[...${key}]]`)) {
        path = path.replace(`[[...${key}]]`, value.join("/"));
      } else if (path.includes(`[...${key}]`)) {
        path = path.replace(`[...${key}]`, value.join("/"));
      }
    }
  }
  return path;
}

type PlasmicHomepageServerProps = DefaultHomepageProps & {
  params?: Promise<Record<string, string | string[] | undefined>>;
  searchParams?: Promise<Record<string, string | string[] | undefined>>;
};

export async function PlasmicHomepageServer(props: PlasmicHomepageServerProps) {
  const { params, searchParams, ...rest } = props;

  const pageRoute = "/";
  const pageParams = (await params) ?? {};
  const pagePath = mkPathFromRouteAndParams(pageRoute, pageParams);

  const $ctx = {
    pageRoute,
    pagePath,
    params: pageParams,
    query: searchParams
  };

  const $serverQueries = await executeServerQueries($ctx);

  return <ClientHomepage {...rest} $serverQueries={$serverQueries} />;
}
